apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: builders-ssl-cert
  namespace: builders
spec:
  secretName: builders-ssl-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: builders.dok3s.srobot.dev
  dnsNames:
    - builders.dok3s.srobot.dev
